# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-27 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registercustomer',
            name='relate',
        ),
    ]
