# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts1', '0003_auto_20180428_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(default=0, max_length=200)),
                ('amount_UGX', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LoanCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('loan_period', models.IntegerField(default=0)),
                ('interest_rate', models.IntegerField(default=0)),
                ('results', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='friends',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='users',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
