# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts1', '0005_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancalculator',
            name='loan_period',
            field=models.CharField(default='', max_length=200),
        ),
    ]
